# Generated by Django 5.1.6 on 2025-03-05 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название категории')),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название вакансии')),
                ('description', models.TextField(verbose_name='Описание вакансии')),
                ('company', models.CharField(max_length=80, verbose_name='Название компании')),
                ('location', models.CharField(max_length=100, verbose_name='Местоположение вакансии')),
                ('date_posted', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название работы')),
                ('company', models.CharField(max_length=80, verbose_name='Название компании')),
                ('experiences', models.PositiveIntegerField(default='Без опыта', max_length=89, verbose_name='Опыт работы в  годах')),
                ('salary', models.PositiveIntegerField(max_length=89, verbose_name='Оклад')),
                ('description', models.TextField(verbose_name='Описание работы')),
                ('skills', models.CharField(max_length=255, verbose_name='Необходимые навыки')),
                ('adress', models.CharField(default='адрес компании', max_length=100, verbose_name='Адрес работы')),
                ('phone', models.CharField(max_length=100, verbose_name='номер телефона')),
                ('email', models.EmailField(max_length=255, verbose_name='Электронная почта')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LaPasionito.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Работа',
                'verbose_name_plural': 'Работы',
            },
        ),
    ]
